name: "dslistpro"

services:
  pg:
    image: bitnami/postgresql:14.15.0
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=albqvxc
      - POSTGRES_PASSWORD=vito123
      - POSTGRES_DB=dslistpro
    volumes:
      - pg-data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: albq.victor@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - pg

volumes:
  pg-data:
  pgadmin-data: